apiVersion: apps/v1
kind: Deployment
metadata:
  name: summit-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summit-app
  template:
    metadata:
      labels:
        app: summit-app
    spec:
      containers: 
      - name: summit-app-pod
        image: 996886234804.dkr.ecr.eu-west-2.amazonaws.com/cloud-summit:1.0
        env:
        - name: AZSVC
          value: "Elastic Kubernetes Service"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: summit-app-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: summit-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: summit-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: aws.tipuric.com 
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: summit-app-svc
                port:
                  number: 80
            path: /
